#! /usr/bin/python3
import sys
from pathlib import Path

if len(sys.argv) != 2:
  print("Usage: " + sys.argv[0].split('/')[-1] + " <FileName>")
  exit()

filePath = Path(sys.argv[1])
outFileName = filePath.parent.as_posix() + '/fmtd_' + filePath.name
left=True
with open(filePath, 'r') as inFile, open(outFileName, 'w') as outFile:
  for line in inFile:
    line = line.rstrip()
    if line == '$$':
      line = '```math' if left else '```'
      left = not left
    outFile.write(line + '\n')

